version: "3.9"

services:
  db:
    image: mysql:8
    container_name: ambisis_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ambisis
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: ./apps/api
    container_name: ambisis_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/ambisis
      JWT_SECRET: supersecret
    ports:
      - "3001:3001"

  web:
    build: ./apps/web
    container_name: ambisis_web
    restart: always
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"

volumes:
  db_data: